sudo: required
services:
    - docker

before_install:
    - docker build -t ersergeant/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ersergeant/docker-react npm run test

language: generic 